Brands pages links
Kuhlman-g/project-kachow pull request #8
Opened 2021-04-26 14:52 UTC by whicke01

Added links in the Brand Index page to a Brand show page.
Added links in the Brand Show page to a Pizza show page.

2021-04-26 18:33 UTC, kaydc18 requested changes

2021-04-26 18:33 UTC, kaydc18 commented on app/assets/stylesheets/_settings.scss
> +// $card-border-radius: 50%;
Make sure you remove commented out code before you submit a PR

2021-04-26 18:33 UTC, kaydc18 commented on app/javascript/react/components/BrandShowContainer.js
> +import {Link} from 'react-router-dom'
I would add spaces between Link and the brackets like useState and useEffect in line 1 for consistency.

2021-04-26 18:33 UTC, kaydc18 commented on app/javascript/react/components/BrandsIndexContainer.js
> +import {Link} from "react-router-dom"
Same as my previous comment. I would just get with the group and choose how you want the syntax styling to look.

2021-04-26 18:33 UTC, kaydc18 commented on app/javascript/react/components/BrandsIndexContainer.js
>          {brandTiles}
this is indented a little too much

2021-04-26 18:33 UTC, kaydc18 commented on app/javascript/react/components/BrandShowContainer.js
>          {pizzaTiles}
I would extract this info into a pizzaTile component to extract your html in lines 32-38

2021-04-26 18:33 UTC, kaydc18 commented on app/javascript/react/components/BrandsIndexContainer.js
>      </div>
I would turn this into a brandTile component

2021-04-26 21:34 UTC, Kuhlman-g commented
Separated HTML portion into separate react components/Tiles

2021-04-27 17:28 UTC, kaydc18 approved these changes
I'm going to approve this, but there are some alignment things that are off. I would just do a little cleaning before you merge.

2021-04-27 17:28 UTC, kaydc18 commented on app/javascript/react/components/BrandTile.js
> +    return(
you could tab line 6 a little less so the <div> sits better inside.

2021-04-27 17:28 UTC, kaydc18 commented on app/javascript/react/components/BrandTile.js
> +    )
take a tab off line 14 too. It looks a little too deep

2021-04-27 17:28 UTC, kaydc18 commented on app/javascript/react/components/BrandsIndexContainer.js
>      <div  className='cell small-11 text-center'>
extra space between your div and className on line 39

2021-04-27 17:28 UTC, kaydc18 commented on app/javascript/react/components/BrandsIndexContainer.js
>          {brandTiles}
since {brandTiles} is not inside the div above (line 38), it should line up with it

2021-04-27 17:28 UTC, kaydc18 commented on app/javascript/react/components/BrandShowTile.js
> +    )
tabbed too far in, but this is aligned well. I would use this example for your PizzaShowTile

2021-04-27 17:28 UTC, kaydc18 commented on app/javascript/react/components/BrandShowContainer.js
>      }
This alignment is off a little bit

2021-04-27 17:28 UTC, kaydc18 commented on app/javascript/react/components/BrandsIndexContainer.js
>    return(
The code inside this return is a little off on alignment too.

2021-04-27 17:36 UTC, merged